# Generated by Django 5.0.6 on 2026-06-06 23:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('medical', 'Appel médical (Hôpital)'), ('ngo_project', 'Projet ONG')], max_length=16)),
                ('category', models.CharField(choices=[('health', 'Santé'), ('emergency', 'Urgence'), ('education', 'Éducation'), ('development', 'Développement'), ('social', 'Social')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='résumé')),
                ('description', models.TextField()),
                ('country', models.CharField(choices=[('CM', 'Cameroun'), ('CI', "Côte d'Ivoire"), ('SN', 'Sénégal'), ('BF', 'Burkina Faso'), ('ML', 'Mali'), ('TG', 'Togo'), ('BJ', 'Bénin'), ('CD', 'RD Congo'), ('NG', 'Nigeria'), ('OTHER', 'Autre')], default='CM', max_length=8)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XAF', max_length=8)),
                ('collected_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('donor_count', models.PositiveIntegerField(default=0)),
                ('cover_image_path', models.CharField(blank=True, max_length=512)),
                ('video_path', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_review', 'En attente de modération'), ('active', 'En cours'), ('closed', 'Clôturée'), ('funded', 'Objectif atteint'), ('rejected', 'Rejetée')], default='draft', max_length=16)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_reason', models.TextField(blank=True)),
                ('budget_justification_path', models.CharField(blank=True, max_length=512)),
                ('consent_form_path', models.CharField(blank=True, max_length=512)),
                ('internal_notes', models.TextField(blank=True)),
                ('moderation_notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='organizations.organization')),
            ],
            options={
                'verbose_name': "Appel à l'aide",
                'verbose_name_plural': "Appels à l'aide",
            },
        ),
        migrations.CreateModel(
            name='FieldUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('media_paths', models.JSONField(blank=True, default=list)),
                ('author_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_updates', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Mise à jour de terrain',
                'verbose_name_plural': 'Mises à jour de terrain',
            },
        ),
        migrations.CreateModel(
            name='FundUsageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount_used', models.DecimalField(decimal_places=2, max_digits=14)),
                ('attachment_paths', models.JSONField(blank=True, default=list)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_usage_reports', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': "Rapport d'utilisation des fonds",
                'verbose_name_plural': "Rapports d'utilisation des fonds",
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'type'], name='campaigns_c_status_adc9cd_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['category', 'country'], name='campaigns_c_categor_b3f9d9_idx'),
        ),
    ]
