# Generated by Django 5.0.6 on 2026-06-06 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XAF', max_length=8)),
                ('method', models.CharField(choices=[('conditional_check', 'Chèque conditionné'), ('direct_transfer', 'Virement direct (hôpital / fournisseur)')], default='direct_transfer', max_length=24)),
                ('beneficiary_name', models.CharField(max_length=255, verbose_name='bénéficiaire (hôpital / fournisseur)')),
                ('purpose', models.TextField(verbose_name='objet de la dépense')),
                ('justification_paths', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'En attente de validation admin'), ('approved', 'Validée (instruction bancaire)'), ('paid', 'Payée (chèque conditionné / virement)'), ('rejected', 'Rejetée')], default='pending', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('bank_reference', models.CharField(blank=True, max_length=128)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='campaigns.campaign')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.profile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Demande de déblocage',
                'verbose_name_plural': 'Demandes de déblocage',
            },
        ),
    ]
