# Generated by Django 5.0.6 on 2026-06-06 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('donation_receipt', 'Reçu de don'), ('campaign_progress', 'Progression cagnotte (tuteur)'), ('disbursement', 'Déblocage des fonds'), ('account', 'Compte / certification')], max_length=32)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Journal e-mail',
                'verbose_name_plural': 'Journaux e-mail',
            },
        ),
    ]
