# Generated by Django 5.0.6 on 2026-06-06 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80, verbose_name='prénom')),
                ('last_name_initial', models.CharField(max_length=2, verbose_name='initiale du nom')),
                ('age', models.PositiveSmallIntegerField()),
                ('is_minor', models.BooleanField(default=False)),
                ('general_situation', models.TextField(help_text='Ex. : « enfant de 7 ans, pathologie nécessitant une opération ».', verbose_name='situation générale')),
                ('display_level', models.IntegerField(choices=[(1, 'Niveau 1 — Anonyme (prénom + initiale, âge, situation)'), (2, 'Niveau 2 — Photo floutée (mineur / accord partiel)'), (3, 'Niveau 3 — Photo nette + vidéo (décharge complète)')], default=1)),
                ('photo_path', models.CharField(blank=True, max_length=512)),
                ('photo_blurred_path', models.CharField(blank=True, max_length=512)),
                ('video_path', models.CharField(blank=True, max_length=512)),
                ('consent_signed', models.BooleanField(default=False, verbose_name='décharge signée')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Profil patient',
                'verbose_name_plural': 'Profils patients',
            },
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='patients.patientprofile')),
            ],
            options={
                'verbose_name': 'Contact tuteur (privé)',
                'verbose_name_plural': 'Contacts tuteurs (privés)',
            },
        ),
    ]
