# Generated by Django 5.0.6 on 2026-06-06 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supabase_user_id', models.UUIDField(db_index=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(choices=[('hospital_agent', 'Assistant social — Hôpital'), ('ngo_agent', 'Agent — ONG'), ('admin', 'Administrateur plateforme'), ('donor', 'Donateur / visiteur enregistré')], default='donor', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('locale', models.CharField(default='fr', max_length=5)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
    ]
