# Generated by Django 5.0.6 on 2026-06-06 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('hospital', 'Service Social — Hôpital / Clinique'), ('ngo', 'ONG / Association')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('legal_status', models.CharField(blank=True, max_length=255, verbose_name='statut légal')),
                ('registration_number', models.CharField(blank=True, max_length=128, verbose_name='n° RCCM / agrément')),
                ('country', models.CharField(default='CM', max_length=8)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('intervention_zones', models.JSONField(blank=True, default=list, verbose_name="zones d'intervention")),
                ('action_domains', models.JSONField(blank=True, default=list, verbose_name="domaines d'action")),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('logo_path', models.CharField(blank=True, max_length=512)),
                ('certification_status', models.CharField(choices=[('pending', 'En attente de vérification'), ('certified', 'Certifiée'), ('suspended', 'Suspendue'), ('rejected', 'Rejetée')], default='pending', max_length=16)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('legal_documents', models.JSONField(blank=True, default=list)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=16)),
                ('premium_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'ordering': ['name'],
            },
        ),
    ]
