import type {
  Campaign,
  CampaignDetail,
  DisbursementRequest,
  DonationPublic,
  Organization,
} from "@/types/api";

/**
 * Données de démonstration utilisées en repli lorsque l'API Django n'est pas
 * encore joignable (développement / aperçu statique). En production, ces données
 * proviennent du backend (`/api/v1/campaigns/`).
 */
const img = (q: string) =>
  `https://images.unsplash.com/${q}?auto=format&fit=crop&w=1200&q=70`;

export const DEMO_CAMPAIGNS: CampaignDetail[] = [
  {
    id: "demo-1",
    type: "medical",
    category: "health",
    title: "Opération du cœur pour Awa, 7 ans",
    slug: "operation-coeur-awa",
    summary:
      "Une opération cardiaque urgente pour permettre à Awa de grandir en bonne santé.",
    country: "CM",
    target_amount: "4500000",
    collected_amount: "2870000",
    currency: "XAF",
    donor_count: 184,
    progress_pct: 63.8,
    cover_image_path: img("photo-1576765608535-5f04d1e3f289"),
    status: "active",
    deadline: "2026-07-20",
    organization_name: "Hôpital Central de Yaoundé — Service Social",
    organization_type: "hospital",
    published_at: "2026-05-01",
    description:
      "Awa, 7 ans, présente une pathologie nécessitant une intervention chirurgicale cardiaque. Le service social de l'Hôpital Central accompagne sa famille pour réunir le montant du devis hospitalier. La cagnotte est entièrement administrée par l'établissement.",
    video_path: "",
    patient: {
      display_name: "Awa N.",
      age: 7,
      is_minor: true,
      general_situation:
        "Enfant de 7 ans, pathologie cardiaque nécessitant une opération.",
      display_level: 1,
      photo_path: "",
      video_path: "",
    },
    field_updates: [],
    fund_usage_reports: [],
  },
  {
    id: "demo-2",
    type: "medical",
    category: "emergency",
    title: "Prise en charge des grands brûlés — Joseph",
    slug: "grands-brules-joseph",
    summary:
      "Soins d'urgence et greffes pour Joseph après un accident domestique.",
    country: "CM",
    target_amount: "2800000",
    collected_amount: "1190000",
    currency: "XAF",
    donor_count: 97,
    progress_pct: 42.5,
    cover_image_path: img("photo-1612277795421-9bc7706a4a34"),
    status: "active",
    deadline: "2026-07-05",
    organization_name: "Hôpital Central de Yaoundé — Service Social",
    organization_type: "hospital",
    published_at: "2026-05-10",
    description:
      "Joseph a été victime de graves brûlures. La prise en charge nécessite plusieurs interventions et un suivi prolongé sous la supervision du service social.",
    video_path: "",
    patient: {
      display_name: "Joseph K.",
      age: 29,
      is_minor: false,
      general_situation:
        "Adulte, brûlures graves nécessitant des greffes successives.",
      display_level: 1,
      photo_path: "",
      video_path: "",
    },
    field_updates: [],
    fund_usage_reports: [],
  },
  {
    id: "demo-3",
    type: "ngo_project",
    category: "education",
    title: "Une école pour le village de Bangou",
    slug: "ecole-bangou",
    summary: "Construire trois salles de classe pour 120 enfants déscolarisés.",
    country: "CM",
    target_amount: "8000000",
    collected_amount: "5200000",
    currency: "XAF",
    donor_count: 312,
    progress_pct: 65,
    cover_image_path: img("photo-1503676260728-1c00da094a0b"),
    status: "active",
    deadline: "2026-09-01",
    organization_name: "Solidarité Santé Afrique",
    organization_type: "ngo",
    published_at: "2026-04-15",
    description:
      "Le projet vise à construire et équiper trois salles de classe afin d'accueillir 120 enfants aujourd'hui privés d'école. Un rapport d'utilisation des fonds est publié à chaque tranche débloquée.",
    video_path: "",
    patient: null,
    field_updates: [
      {
        id: "fu-1",
        campaign: "demo-3",
        title: "Fondations terminées",
        content:
          "Les fondations des trois salles sont coulées. Merci à tous les donateurs !",
        media_paths: [],
        created_at: "2026-05-20",
      },
    ],
    fund_usage_reports: [
      {
        id: "fr-1",
        campaign: "demo-3",
        title: "Tranche 1 — matériaux",
        description: "Achat de ciment, briques et fer à béton.",
        amount_used: "1800000",
        attachment_paths: [],
        created_at: "2026-05-18",
      },
    ],
  },
  {
    id: "demo-4",
    type: "ngo_project",
    category: "development",
    title: "Accès à l'eau potable — forages solaires",
    slug: "eau-potable-forages",
    summary: "Installer 5 forages solaires pour 2 000 habitants.",
    country: "TG",
    target_amount: "6000000",
    collected_amount: "980000",
    currency: "XAF",
    donor_count: 58,
    progress_pct: 16.3,
    cover_image_path: img("photo-1594761051556-eca6b5d7fa9c"),
    status: "active",
    deadline: "2026-10-10",
    organization_name: "Solidarité Santé Afrique",
    organization_type: "ngo",
    published_at: "2026-05-22",
    description:
      "Installation de forages équipés de pompes solaires pour garantir un accès durable à l'eau potable dans des zones rurales reculées.",
    video_path: "",
    patient: null,
    field_updates: [],
    fund_usage_reports: [],
  },
];

export const DEMO_DONORS: DonationPublic[] = [
  {
    id: "d1",
    donor_name: "Diaspora CM",
    amount: "50000",
    currency: "XAF",
    message: "Courage à la famille 🙏",
    created_at: "2026-05-30",
  },
  {
    id: "d2",
    donor_name: "Donateur anonyme",
    amount: "25000",
    currency: "XAF",
    message: "",
    created_at: "2026-05-29",
  },
  {
    id: "d3",
    donor_name: "Association Espoir",
    amount: "100000",
    currency: "XAF",
    message: "Toute notre solidarité.",
    created_at: "2026-05-27",
  },
];

export const DEMO_DISBURSEMENTS: DisbursementRequest[] = [
  {
    id: "disb-1",
    campaign: "demo-1",
    campaign_title: "Opération du cœur pour Awa, 7 ans",
    amount: "1500000",
    currency: "XAF",
    method: "direct_transfer",
    beneficiary_name: "Hôpital Central de Yaoundé — Bloc Chirurgical",
    purpose: "Acompte sur actes chirurgicaux & réanimation",
    justification_paths: ["legal-docs/devis-bloc-awa.pdf"],
    status: "approved",
    admin_notes: "Devis vérifié et conforme au barème hospitalier.",
    bank_reference: "VIR-2026-0810-09",
    reviewed_at: "2026-05-15T10:00:00Z",
    paid_at: "2026-05-16T14:30:00Z",
    created_at: "2026-05-14T09:00:00Z",
  },
  {
    id: "disb-2",
    campaign: "demo-3",
    campaign_title: "Une école pour le village de Bangou",
    amount: "1800000",
    currency: "XAF",
    method: "conditional_check",
    beneficiary_name: "Quincaillerie Générale du Littoral",
    purpose: "Tranche 1 : Achat de ciment, fer à béton et agrégats",
    justification_paths: ["legal-docs/facture-quincaillerie-bangou.pdf"],
    status: "paid",
    admin_notes: "Validation après audit des devis fournisseurs.",
    bank_reference: "CHK-7740219",
    reviewed_at: "2026-05-17T11:00:00Z",
    paid_at: "2026-05-18T16:00:00Z",
    created_at: "2026-05-16T15:20:00Z",
  },
  {
    id: "disb-3",
    campaign: "demo-2",
    campaign_title: "Prise en charge des grands brûlés — Joseph",
    amount: "500000",
    currency: "XAF",
    method: "direct_transfer",
    beneficiary_name: "Pharmacie Principale Hôpital Central",
    purpose: "Achat d'antiseptiques et pansements spécialisés pour greffe",
    justification_paths: ["legal-docs/bon-pharmacie-joseph.pdf"],
    status: "pending",
    admin_notes: "",
    bank_reference: "",
    reviewed_at: null,
    paid_at: null,
    created_at: "2026-05-25T11:00:00Z",
  },
];

export const DEMO_ORGANIZATIONS: Organization[] = [
  {
    id: "org-1",
    type: "hospital",
    name: "Hôpital Central de Yaoundé — Service Social",
    legal_status: "Établissement Public de Santé",
    registration_number: "MINSANTE-HCY-2024",
    country: "CM",
    city: "Yaoundé",
    intervention_zones: ["Centre", "Littoral"],
    action_domains: ["Santé infantile", "Chirurgie cardiaque", "Urgence"],
    description:
      "Service social chargé de l'accompagnement des patients démunis et de l'administration des cagnottes de santé.",
    website: "https://hopitalcentral.cm",
    contact_email: "social@hopitalcentral.cm",
    contact_phone: "+237 222 23 45 67",
    certification_status: "certified",
    certified_at: "2026-01-10T10:00:00Z",
    is_certified: true,
    is_premium: true,
    created_at: "2026-01-01T08:00:00Z",
  },
  {
    id: "org-2",
    type: "ngo",
    name: "Solidarité Santé Afrique",
    legal_status: "ONG à but non lucratif",
    registration_number: "ONG-SSA-2022-88",
    country: "CM",
    city: "Douala",
    intervention_zones: ["Cameroun", "Togo"],
    action_domains: ["Éducation", "Eau potable", "Santé communautaire"],
    description:
      "ONG œuvrant pour l'accès aux soins et à l'éducation en milieu rural.",
    website: "https://solidaritesanteafrique.org",
    contact_email: "contact@solidaritesanteafrique.org",
    contact_phone: "+237 699 00 11 22",
    certification_status: "certified",
    certified_at: "2026-02-15T09:00:00Z",
    is_certified: true,
    is_premium: false,
    created_at: "2026-02-01T09:00:00Z",
  },
];

export const asListItem = (c: CampaignDetail): Campaign => c;

