# Generated by Django 5.0.6 on 2026-06-06 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='XAF', max_length=8)),
                ('platform_support_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('donor_name', models.CharField(blank=True, max_length=255)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('gateway', models.CharField(choices=[('cinetpay', 'CinetPay (Mobile Money Afrique francophone)'), ('campay', 'Campay (Orange / MTN Cameroun)'), ('flutterwave', 'Flutterwave (cartes diaspora)')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=16)),
                ('transaction_ref', models.CharField(blank=True, db_index=True, max_length=128)),
                ('gateway_payload', models.JSONField(blank=True, default=dict)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('receipt_sent', models.BooleanField(default=False)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'indexes': [models.Index(fields=['status', 'gateway'], name='donations_d_status_a70ed9_idx')],
            },
        ),
    ]
